name: Add Patience Quotes to PR
on:
  pull_request:
    types: [opened]

jobs:
  add_quotes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add Patience Quote
        run: |
          quotes=(
            "Patience is a virtue."
            "Good things come to those who wait."
            "Patience, grasshopper."
            # Add more quotes here
          )
          random_index=$(( $RANDOM % ${#quotes[@]} ))
          patience_quote=${quotes[$random_index]}
          echo "::set-output name=quote::$patience_quote"

      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const quote = process.env.quote;
            const message = `> ${quote}\n\nStay patient and keep coding! 🚀`;
            const { data: comment } = await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message,
            });
